[versions]
crate = "4.0.0-RC.4"

[libraries]
velocity-api = "com.velocitypowered:velocity-api:3.4.0-SNAPSHOT"
wordweaver = "io.github.milkdrinkers:wordweaver:0.0.7"
crate-api = { module = "io.github.milkdrinkers:crate-api", version.ref = "crate" }
crate-yaml = { module = "io.github.milkdrinkers:crate-yaml", version.ref = "crate" }
colorparser = "io.github.milkdrinkers:colorparser-velocity:4.1.0"
github-api = "org.kohsuke:github-api:1.330"
geyser = "org.geysermc.geyser:api:2.9.0-SNAPSHOT"
floodgate = "org.geysermc.floodgate:api:2.2.5-SNAPSHOT"
bstats = "org.bstats:bstats-bukkit:3.1.0"

[plugins]
blossom = "net.kyori.blossom:2.2.0"
jetbrains-gradle = "org.jetbrains.gradle.plugin.idea-ext:1.3"
run-velocity = "xyz.jpenilla.run-velocity:3.0.2"
shadow = "com.gradleup.shadow:9.2.2"
